# Required PROXMOX_URL, PROXMOX_USERNAME, PROXMOX_TOKEN variables which are
# described in the readme. Make sure to set them in GitLab.
test-packer:
  stage: test
  image: golang:1.18.2
  variables:
    PM_API_TOKEN_ID: ${PROXMOX_USERNAME}
    PM_API_TOKEN_SECRET: ${PROXMOX_TOKEN}
  script:
    - apt update
    - apt install unzip
    - wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.8.2/packer_1.8.2_linux_amd64.zip
    - unzip /tmp/packer.zip
    - mv packer /usr/local/bin
    - wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip
    - unzip /tmp/terraform.zip
    - mv terraform /usr/local/bin
    - cd test
    # Use gotestsum to generate a JUnit-like report.
    - go run gotest.tools/gotestsum@latest --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: test/report.xml
