#!/bin/sh

# Enable community repository.
sed -i 's:# \(.*/v.*/community\):\1:' /etc/apk/repositories
apk update

# Setup QEMU guest agent.
apk add qemu-guest-agent
# Set device path to /dev/vport2p1.
sed -i 's:/dev/virtio-ports/org.qemu.guest_agent.0:/dev/vport2p1:' /etc/init.d/qemu-guest-agent
# Add and start OpenRC service.
rc-update add qemu-guest-agent
rc-service qemu-guest-agent start
